execute:
  freeze: auto

project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

format:
  html:
    theme: solar

website: 
  title: "EC311 Intermediate Micro"
  repo-url: https://gituhub.com/dyasui/EC-311
  repo-actions: [edit, source, issue]
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: Slides/index.qmd
      - text: "Labs"
        href: Labs/index.qmd
  announcement: 
    icon: clipboard2-check-fill
    dismissable: true
    content: "Announcements appear here"
    type: warning
    position: below-navbar
