execute:
  freeze: auto

project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

format:
  html:
    theme: 
      light: flatly
      dark: darkly

website: 
  title: "EC311 Intermediate Micro"
  repo-url: https://gituhub.com/dyasui/EC-311
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: Slides/index.qmd
      - text: "Labs"
        href: Labs/index.qmd
      - text: "Exams"
        href: "Exams/index.qmd"
  announcement: 
    icon: clipboard2-check-fill
    dismissable: true
    content: "Additional practice problems posted under the 'Labs' tab"
    type: warning
    position: below-navbar
