execute:
  freeze: auto

project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

format:
  html:
    theme: 
      light: flatly
      dark: darkly

website: 
  title: "EC311 Intermediate Micro"
  repo-url: https://gituhub.com/dyasui/EC-311
  repo-actions: [edit, source, issue]
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: Slides/index.qmd
      - text: "Labs"
        href: Labs/index.qmd
      - text: "Practice Exams"
        href: "Exams/index.qmd"
  announcement: 
    icon: clipboard2-check-fill
    dismissable: true
    content: "No Wednesday Office Hour, now on Friday: 12:30 in PLC 525"
    type: warning
    position: below-navbar
  announcement: 
    icon: clipboard2-check-fill
    dismissable: true
    content: "Correct Achieve Course Code is fm6j5k"
    type: warning
    position: below-navbar
