---
title: "Home"
---

## Spring 2025 Class Details

:::: {.columns}
::: {.column width="50%"}

**Instructor:** [Dante Yasui](https://github.com/dyasui)

**Office Hours:** Mon 10am in [Tykeson hall](https://map.uoregon.edu/9195592d9), Fri 12:30m in PLC 535

:::

::: {.column width="50%"}

**Class Location:** [Straub 145](https://map.uoregon.edu/6c8b3f7f2)

**Class Day & Time:** Mon & Wed - 4:00-6:00pm

:::

::::

### TA Office Hours

- **Alexander Pabst**: Tues 10:00-10:50 am in PLC 406

- **Eugene Mensah**: Monday 8:00-9:00 am in PLC 418

## Tentative Schedule

| **Week** |    **Topic**    | **Assignments** |
|:--------:|:----------------|:----------------|
|    1     | Ch 2: [Intro](Slides/#intro-and-syllabus-day) & [Review](Slides/#calculus-review)  | [Quiz 1](https://canvas.uoregon.edu/courses/260984/quizzes/387474) & Ch 2 HW |
|    2     | Ch 4: [Utility & Indifference](Slides/#consumer-behavior) | [Quiz 2](https://canvas.uoregon.edu/courses/260984/quizzes/387476) |
|    3     | Ch 4: [Budgets & Optimization](Slides/#utility-maximization) | [Quiz 3](https://canvas.uoregon.edu/courses/260984/quizzes/387475) & Ch 4 HW |
|    4     | Ch 5: [Demand](Slides/#Demand)  | [Quiz 4](https://canvas.uoregon.edu/courses/260984/quizzes/387478) & Ch 5 HW |
|    5     | **MIDTERM** | **Wednesday, April 30th** |
|    6     | Ch 6: [Production](Slides/#production) | Ch 6 HW |
|    7     | Ch 7: [Cost Functions](Slides/#cost-functions) | [Quiz 5](https://canvas.uoregon.edu/courses/260984/quizzes/387477) & Ch 7 HW |
|    8     | Ch 8: [Supply](Slides/#market-supply) | [Quiz 6](https://canvas.uoregon.edu/courses/260984/quizzes/387479) & Ch 8 HW |
|    9     | Ch 9: [Monopoly](Slides/#monopoly) | Ch 9 HW |
|   10     | Ch 11: [Imperfect Competition](Slides/#imperfect-competition) | [Quiz 7](https://canvas.uoregon.edu/courses/260984/quizzes/387473) & Ch 11 HW |
| Finals | **Wednesday, June 11, 2:45pm** | Exam |

### Course Grade Breakdown

For more details, read the [Syllabus](Syllabus/main.pdf) below

| Assignment  | Grade Weight | 
|:------------|:------------:|
| Participation | **5%** |
| Achieve Homework | **20%** |
| Canvas Quizzes | **15%** |
| Midterm Exam | **30%** |
| Final Exam | **30%** |

### Achieve Access

Follow [this link](https://mhe.my.site.com/macmillanlearning/s/article/Students-Register-for-Achieve-courses-via-your-school-s-LMS)
to register for our course in Achieve once you have purchased an access code.

The course code is `fm6j5k`.

## Syllabus

```{=html}
<details>
  <summary>Spring 2025 Syllabus PDF</summary>
  <a class="btn btn-primary btn-lg cv-download" href="Syllabus/main.pdf" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download
  </a>
  <div class="embed-container">
    <iframe src="Syllabus/main.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```
