---
name: optimization
---

## Finding Maximum (or Minimum) Values

When we have a continuos function, we can use calculus to find where the largest (or smallest) value will occur

- Recall that when the [derivative]{.hii} is [positive]{.h}, then the function is *increasing*

- and when the derivative is [negative]{.h}, then the function is *decreasing*

. . .

<br>

- Where the function is neither increasing nor decreasing, it's either because it's as high as it goes!

## Examples

Let's look at an example:

$$f(x,y) = 1 - x^2 - y^2 + 2x + 4y$$

How can we figure out where the maximum value of $f()$ will occur?

. . .

- Let's start by taking some derivatives!

. . .

:::: {.columns}

::: {.column width="50%"}
- Partial w.r.t. $x$

:::: {.fragment}
\begin{align*}
\dfrac{df}{dx} &= -2x + 2 \\
\end{align*}
::::
:::

::: {.column width="50%"}
- Partial w.r.t. $y$

:::: {.fragment}
\begin{align*}
\dfrac{df}{dy} &= -2y + 4 \\
\end{align*}
::::

:::
::::

---

## Examples

Let's look at an example:

$$f(x,y) = 1 - x^2 - y^2 + 2x + 4y$$

:::: {.columns}

::: {.column width="50%"}
- Partial w.r.t. $x$

:::: {.fragment}
\begin{align*}
\dfrac{df}{dx} &= -2x + 2 \\
\end{align*}
::::
:::

::: {.column width="50%"}
- Partial w.r.t. $y$

:::: {.fragment}
\begin{align*}
\dfrac{df}{dy} &= -2y + 4 \\
\end{align*}
::::

:::
::::

---

## What do these derivatives tell us?

- Whether $f()$ is *increasing* or *decreasing*

:::: {.columns}

::: {.column width="50%"}
- If $x<1$, we know $f()$ is *increasing* with $x$
- If $x>1$, we know $f()$ is *decreasing* with $x$
:::

::: {.column width="50%"}
- If $y<2$, we know $f()$ is *increasing* with $y$
- If $y>2$, we know $f()$ is *decreasing* with $y$
:::

::::
---

## Examples

$$f(x,y) = 1 - x^2 - y^2 + 2x + 4y$$

Let's take an example coordinate and see if it's a *maximum*:

starting at the origin:

> $(x=0,y=0)$

At $(x=0, y=0)$, $f(0,0) = 1$

- but $\dfrac{df}{dx} = 2$ which tells us we could increase $f()$ by increasing $x$
- also, $\dfrac{df}{dy} = 4$, so we could also increase $f()$ by increasing $y$

. . .

So we know $(0,0)$ is not a maximum, and we know which direction to go to look for one

---

## Examples

$$f(x,y) = 1 - x^2 - y^2 + 2x + 4y$$

Let's go up in $x$ and $y$:

> $(x=1,y=1)$

$f(1,1) = 5$ which is higher, but is it a *maximum*?

. . .

- $\dfrac{df}{dx} = 0$
- but, $\dfrac{df}{dy} = 2$, so we still could increase $f()$ by increasing $y$

---

## Examples

$$f(x,y) = 1 - x^2 - y^2 + 2x + 4y$$

Let's go up in $x$ and $y$:

> $(x=2,y=2)$

$f(2,2) = 5$ which isn't any higher than $(1,1)$

. . .

- $\dfrac{df}{dx} = -2$, this tells us we went too far in $x$!
- $\dfrac{df}{dy} = 0$, so we should stop increasing $y$

---

## What *is* the max of this function?

Where both partial derivatives are *equal to zero*: 

- $\dfrac{df}{dx} = 0 \Rightarrow x = 1$
- $\dfrac{df}{dy} = 0 \Rightarrow x = 2$

$f(1,2) = 6$ is the maximum value!

---

## Another Example

$$f(x,y) = \sqrt{x^2+y^2}$$

What are the partial derivatives?

. . .

:::: {.columns}

::: {.column width="50%"}

What is the [partial derivative of $x \rightarrow \dfrac{df}{dx}$]{.hi}?

::: {.fragment}
\begin{align*}
\dfrac{d}{dx}(x^2+y^2)^\frac{1}{2} & = \\
 & \frac{1}{2} (x^2+y^2)^{-\frac{1}{2}} (2x) \\
\dfrac{df}{dx} = 0 & \Rightarrow x = 0 \\
\end{align*}
:::

:::

::: {.column width="50%"}

What is the [partial derivative of $y \rightarrow \dfrac{df}{dx}$]{.hi}?

::: {.fragment}
\begin{align*}
\dfrac{d}{dy}(x^2+y^2)^\frac{1}{2} & = \\
 & \frac{1}{2} (x^2+y^2)^{-\frac{1}{2}} (2y) \\
\dfrac{df}{dy} = 0 & \Rightarrow y = 0 \\
\end{align*}
:::

:::
:::: 

---
