---
name: syllabus 
---

## Class Information {.smaller}

- [**Schedule:**]{.hi} Monday & Wednesday in Straub 145
- [**Office Hours:**]{.hi} Monday 10-11am, Wednesday 1-2pm
- [Attendance]{.hii} is important to your learning experience
    - A lot goes on in the class that may be hard to understand just from lecture slides

. . .

[Lectures]{.hi}

- They will be dynamic, with me asking general questions and expecting answers from you

- There will be in-class problems for you to complete and which will be a part of your participation grade

- On ocassion I will use the whiteboard to make graphs or to answer math questions

---

## Expectations

[Prerequisites]{.hi}

- EC 201: Intro to Microeconomics
- MATH 111: 
    - MATH 241: Calculus 1 (Recommended but not required)
    - I'll give you a crashcourse in what we'll need from calculus in the next lecture

---

## Expectations

[What to Expect from the Course]{.hi}

- The course involves a healthy mix of math and economic theory
    - The math is relatively straightforward, but it requires a good grasp on the theory to properly interpret it 
- More importantly than committing the theory to memory, the goal is to think like an economist
    - There is a set logic in the theory that we will see and it should lead to predictable conclusions

. . .

- [I recognize that perhaps all of you are here for the requirement in your own programs, so my aim is to make it as relevant and interesting as possible]{.tiny}

- [I'm not trying to convert you into economists, but rather have you takeaway things that you can apply in your own careers]{.tiny}

---

## Assignments {.smaller}

[Achieve Online Learning]{.hi}

::: {.incremental}
- You [MUST]{.h} register for the course through Achieve
- This is where you will complete your homework 
- It also gives you access to the digital version of the textbook
- The course code is [xu5rmk]{.hp}
- Your lowest homework grade will be dropped
- 1 day grace period (with 5% penalty) $\rightarrow$ no submissions allowed after that
:::

[Canvas Quizzes]{.hi}

::: {.incremental}
- Weekly quizzes that will help you get accustomed to how test questions will look
- Roughly 10 questions with only one attempt allowed
- Your lowest homework grade will be dropped
- No late submissions allowed
:::

--- 

## Grades {.smaller}

:::: {.columns}

::: {.column width="50%"}
[Homework]{.hi}

::: {.incremental}
- Achieve Homework (20%)
    - [8 Assignments]{.h }
    - [Due on Mondays of week after they are assigned at 11:59 pm]{.hi-red}
        - The last assignments will be due on the Saturday before Finals week
- Canvas Quizzes (15%)
    - [7 Quizzes]{.h}
    - [Due on Mondays of week after they are assigned at 11:59 pm]{.hi-red}
:::

:::

::: {.column width=50%}
[Exams]{.hi}

::: {.incremental}
- Midterm (30%)
    - [Week 5 - Wednesday at 4:00]{.hi-red}
- Final (30%)
    - [June 11 - Wednesday at 2:45]{.hi-red}
:::

:::

::::

--- 

## Grades 

[Participation]{.hi}

::: {.incremental}
- I'll randomly select someone to share their answer to lecture problems 
   - Being correct is not important, but rather that you attempted it
- Everyone will eventually be called upon so you cannot escape it
:::

---

## Attendence Wheel!

```{=html}
<iframe width="780" height="500" src="https://wheelofnames.com/84r-qq7" title="Wheel of Names!"></iframe>
```

---

## Course Website

```{=html}
<iframe width="780" height="500" src="https://dyasui.github.io/EC-311/" title="Class Site"></iframe>
```
